### ISSUE TITLE
Add Steve Jobs quotes

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#155]
## Description
We have some vaccant space at bottom of home page, We can fill by adding famous `Steve jobs` quotes.

## Mocks
![issue1](https://user-images.githubusercontent.com/47811606/107911726-1b0a7080-6f83-11eb-8e7c-a7e340879673.png)

### Update [Required]
- [x] [Must be Jobs quote]
### Enhancement to Update [Optional]
- [x] [Add -Steve Jobs as a writer name after the quote in next line]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by anubhavsingh16** [comment]
> I want to work on it

Send a clean PR ASAP.

**Comment by Neox63** [comment]
I'm on it, you'll get the PR in 1h max.

**Comment by Neox63** [comment]
Done, let me know if you want me to change anything about it.

**Comment by nilisha-jais** [comment]
> > I want to work on it
> 
> Send a clean PR ASAP.

Should I work or is it done. I planned to add a slideshow of quotes

**Comment by anubhavsingh16** [comment]
> > > I want to work on it
> > 
> > 
> > Send a clean PR ASAP.
> 
> Should I work or is it done. I planned to add a slideshow of quotes

Send your PR with changes I mentioned in @Neox63 PR.

**Comment by Neox63** [comment]
Hey, thank you for merging. But you merged the 2 PR's and there's huge incoherences in the code rn. There is my script in the js folder (quote.js) that references a deleted tag in index.html (because of the merge of the 2nd PR) AND the script tag of @nilisha-jais that references the 'spam' id at line 845.

It's very unlogical and it make the code heavier for nothing. i read the PR of @nilisha-jais and tbh, the script should not work like that.  

I saw severals things in the @nilisha-jais 's PR that is not good for a good 2021 JS code : 

First of all, you are using innerHTML, this is REALLY dangerous and may cause many XSS flaws in the website. You should not use it for something like that. 

Second point, you are making and array with var, this cause hoisting and it's not good for the readability and performance.

Third point, in the array, the class 'quote' is named 'quote;', so the CSS code doesn't apply to it as you call the .quote selector in the CSS file.

Fourth point, you probably took the structure of HTML in my PR, this is totally OK but there is empty tag : 'span.quote-notation' should not be empty, i removed the tag in my second PR as i just put the quote signs in the array directly. You can also delete the .quote-notation in CSS.

Fifth point, using ' ` ' (template strings) in the array is not good for performance as you append 0 variables to it. It slows down the script.

And lastly, i think you should use .js file directly instead of making a script tag in the source code. It's way better for readability.

That's pretty all the mistakes i saw (I'm a Javascript dev and i'm very annoying with theses standards, i'm sorry but i had to say it x) )

You should merge just one PR at once. RN the code is working, but my js script is useless as the tag was deleted by @nilisha-jais 's PR. 

I can make another PR if you want where i clean all of this. Just tell me ! 

PS : Theses are just advices, don't take it as an offense, i just like well written code ! :)

**Comment by Neox63** [comment]
( @anubhavsingh16 )
